create table "public"."editors" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" uuid,
    "task_id" bigint
);


alter table "public"."editors" enable row level security;

CREATE UNIQUE INDEX editors_pkey ON public.editors USING btree (id);

alter table "public"."editors" add constraint "editors_pkey" PRIMARY KEY using index "editors_pkey";

alter table "public"."editors" add constraint "editors_task_id_fkey" FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE not valid;

alter table "public"."editors" validate constraint "editors_task_id_fkey";

alter table "public"."editors" add constraint "editors_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE not valid;

alter table "public"."editors" validate constraint "editors_user_id_fkey";

grant delete on table "public"."editors" to "service_role";

grant insert on table "public"."editors" to "service_role";

grant references on table "public"."editors" to "service_role";

grant select on table "public"."editors" to "service_role";

grant trigger on table "public"."editors" to "service_role";

grant truncate on table "public"."editors" to "service_role";

grant update on table "public"."editors" to "service_role";


