-- Links between whole documents, made by an annotator on a document-level
-- task: "this document relates to that one", with relation labels.
--
-- Stored between assignments rather than documents, so every annotator's
-- links stay their own (as their annotations do) and go when the assignment
-- does. A link only ever lives on the assignment that made it; the target's
-- "Linked by" list is read from here, not stored a second time. Both ends
-- belong to the same task and annotator — the server enforces that on save.

CREATE TABLE IF NOT EXISTS public.document_relations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  from_assignment_id bigint NOT NULL REFERENCES public.assignments (id) ON DELETE CASCADE,
  to_assignment_id bigint NOT NULL REFERENCES public.assignments (id) ON DELETE CASCADE,
  labels public.relation_labels[] NOT NULL DEFAULT '{}',
  CONSTRAINT document_relations_not_self CHECK (from_assignment_id <> to_assignment_id),
  CONSTRAINT document_relations_unique UNIQUE (from_assignment_id, to_assignment_id)
);

-- "Linked by" looks relations up by their target.
CREATE INDEX IF NOT EXISTS document_relations_to_assignment_id
  ON public.document_relations (to_assignment_id);

-- Like every other table: reached only through the server, never directly
-- through the Supabase API.
ALTER TABLE public.document_relations ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON public.document_relations FROM anon, authenticated;
REVOKE ALL PRIVILEGES ON SEQUENCE public.document_relations_id_seq FROM anon, authenticated;
