describe('Navigate to projects and test functionality ', () => {
      
    it('Enter projects and Add, Delete and Edit ', () => {
        cy.login()
        cy.get('a[data-test="Projects-link"]').click()
        cy.wait(1000) 
        cy.addProject('Deletetest')
        cy.addProject('Deletetest')
        cy.addProject('Deletetest')
        cy.addProject('Deletetest')
        cy.get('a[data-test="Edit-project-link"]').eq(0).click()
        cy.addTask('delete test')
        cy.addTask('delete test')
        cy.addTask('delete test')
        cy.addTask('delete test')
        cy.wait(1000)
        cy.get('[data-test="Checkbox"]').eq(0).check()
        cy.wait(1000)
        cy.get('[data-test="Checkbox"]').eq(2).check()
        cy.wait(1000)
        cy.get('button[data-test="remove-selected-rows"]').eq(1).click({force: true}) 
        cy.wait(1000)
        cy.get('button').contains('Confirm').click()
        cy.wait(1000)
        cy.reload()
        cy.get('a[data-test="View-task"]').should("have.length", 2)  
        cy.wait(1000)
        cy.get('button[data-test="remove-all"]').eq(1).click({force: true}) 
        cy.get('button').contains('Confirm').click()
        cy.reload()
        cy.get('a[data-test="View-task"]').should("have.length", 0) 
        cy.get('a[data-test="Projects-link"]').click()
        cy.wait(1000)
        cy.get('[data-test="Checkbox"]').eq(0).check()
        cy.wait(1000)
        cy.get('[data-test="Checkbox"]').eq(2).check()
        cy.wait(1000)
        cy.get('button[data-test="remove-selected-rows"]').click({force: true}) 
        cy.reload()
        cy.get('a[data-test="Edit-project-link"]').should("have.length", 2) 
        cy.reload()
        cy.wait(1000)
        cy.get('button[data-test="remove-all"]').eq(0).click() 
        cy.wait(1000)
        cy.get('button').contains('Confirm').click()
        cy.reload()
        cy.get('a[data-test="Edit-project-link"]').should("have.length", 0) 
        cy.reload()
        cy.wait(1000)
        //start editing tasks
        cy.addProject('Edittest')
        cy.get('a[data-test="Edit-project-link"]').eq(0).click()
        cy.addTask('test')
        cy.addTask('test')
        cy.get('button[data-test="Documents"]').click()
        cy.get('input[type=file]').selectFile('./cypress/support/Test.txt')
        cy.get('td').contains('Test.txt').should('exist')
        cy.get('a[data-test="Projects-link"]').click
    })
})